### ISSUE TITLE
ELAT

### ISSUE THREAD

**Issue by Beercow** [InQuest/awesome-yara#2]
The EventShot script simply takes a snapshot of the event log(s) you select, then takes a second snapshot after you're done with your analysis, diffs the two files and parses the output. EventScan, can either scan the live system event logs against the EventLogIndicators directory of yara sigs or you can place event log files in the SCAN dir and search it with your yara sigs.
https://github.com/reed1713/ELAT

**Comment by rshipp** [comment]
Thanks for the suggestion, looks like a neat tool.
