### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by ruppde** [InQuest/awesome-yara#21]
- no yara rules in there (but sigma which is different), remove it? https://github.com/Loginsoft-Research/detection-rules

- mikesxrs YARA Rules Collection might be the biggest but the last change was in 16 Nov 2018 and 2 years is a lot in this business. so maybe pass on the trophy?

**Comment by pedramamini** [comment]
@ruppde thanks for the recommendations and apologies for the late response. We've completely dropped the ball on github.com public repo notifications. Making these changes now.

**Comment by SecT0uch** [comment]
The trophy is still on the outdated mikesxrs repo. Which up-to-date source would you recommend ?

**Comment by pedramamini** [comment]
Maybe we just drop the Trophy for now.... there's no single best repo that comes to mind at the moment.
