### ISSUE TITLE
Resources on a wide range of topics

### ISSUE THREAD

**Issue by hyuunnn** [InQuest/awesome-yara#56]
### Guideline
* <a href="https://github.com/Neo23x0/YARA-Performance-Guidelines">Yara Performance Guidelines</a>
* <a href="https://github.com/Neo23x0/YARA-Style-Guide">YARA-Style-Guide</a>

### Videos & Slides
* <a href="https://www.youtube.com/watch?v=mQ-mqxOfopk">Finding Evil with YARA</a>
* <a href="https://www.youtube.com/watch?v=fbidgtOXvc0">SAS2018: Finding aliens, star weapons and ponies with YARA</a>
* <a href="https://www.youtube.com/watch?v=DQXpdEvyasc">Costin Raiu - Combining code similarity with Yara to find goodies</a>
* <a href="https://www.youtube.com/playlist?list=PL8OlALxRcWsSEPtN6AujulTHVc9HZMwso">YARA Rule Processing Sessions - Florian Roth</a>
* <a href="https://securelist.com/yara-webinar-follow-up/96505/">Upping the APT hunting game: learn the best YARA practices from Kaspersky</a>
* <a href="https://www.youtube.com/watch?v=aaV7UieJ_l4">Star-Gazing | Using a Full Galaxy of YARA Methods to Pursue an Apex Actor | By Greg Lesnewich</a>
* <a href="https://github.com/g-les/YARA-PE-Features">Lightweight Binary Similarity - YARA Using PE Features for Quick Wins</a>
* <a href="https://www.youtube.com/watch?v=Dz0C55Azn1Y">DEF CON 26 - Andrea Marcelli - Looking for the perfect signature an automatic YARA rules</a>

**Comment by JosiahRaySmith** [comment]
Love it @hyuunnn.  Can you please make a PR with these additions?
