### ISSUE TITLE
What happened to androguard?

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [InQuest/awesome-yara#58]
What happened? It still exits. I saw it got deleted from a repo.

**Comment by HydraDragonAntivirus** [comment]
https://github.com/Yara-Rules/rules

**Comment by HydraDragonAntivirus** [comment]
https://github.com/MindMac/androguard-yara Okay I found something.

**Comment by JosiahRaySmith** [comment]
Added into tools section
